spring.datasource.url=jdbc:postgresql://postgres:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=validate

jwt.secret=zZ6vtr9CwXrblBwJApb6VqQeJtHpiNQd9M+zMnCFHtcbTw4EV4gkcCH5z0CvFIUxGTwsChhusD3DJxknYpSTjw==
jwt.expiration-ms=86400000