spring.application.name=futinform

spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate

spring.datasource.driverClassName=org.postgresql.Driver

spring.profiles.active=local

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000